name: Run Tox Tests

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11-dev']
        pandas-presence: ['with_pandas', 'without_pandas']
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      PANDAS_PRESENCE: ${{ matrix.pandas-presence }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        PYTHON_ENV="py$(echo $PYTHON_VERSION | sed 's/\.//;s/\-dev//')"
        tox -e "${PYTHON_ENV}-${PANDAS_PRESENCE}"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.10
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: PYTHON_VERSION,PANDAS_PRESENCE
